### ISSUE TITLE
The OT_TIME_SYNC doesn't work

### ISSUE THREAD

**Issue by taraskornuta** [Cascoda/cascoda-sdk#6]
Hi
I try to use otNetworkTimeSetSyncPeriod() and some other APIs from network_time.h (But turns out that I don't need it)
And to use time APIs it was required to enable OT_TIME_SYNC in CMake. When I did it, the project wouldn't compile anymore. 
I use Windows 10 and Chili2D module
[build_log.txt](https://github.com/Cascoda/cascoda-sdk/files/5678037/build_log.txt)

**Comment by CiaranWoodward** [comment]
Hi Taras, thanks for reporting. Unfortunately OT_TIME_SYNC is an openthread library feature that requires an IEEE 802.15.4-2015 radio, but the CA-8211 is an IEEE 802.15.4-2006 radio, so it cannot be supported on current hardware. I think all I can do is set the option to hidden to prevent confusion.

For obtaining the current time, openthread also contains helper libraries for SNTP, which can enable that. Would that solve your use case? The OT_TIME_SYNC feature is to get a very high precision network timestamp, and is a non-standard Thread feature for specialist use cases.

**Comment by taraskornuta** [comment]
Hi @CiaranWoodward
Yes, I found an SNTP client and it solves my task

**Comment by CiaranWoodward** [comment]
I hid the non-functional OT_ CMake options in 272e555346ca80da8f5d5c3a8566b3d124304c1b, which is the latest v0.14 release of the Cascoda SDK
