### ISSUE TITLE
Problems in Thread Commissioning App

### ISSUE THREAD

**Issue by rohithanayady** [Cascoda/cascoda-sdk#7]
i am created a thread network uisng EFR32MG12 as RCP and BeagleBone as Border Router...i have faced some issues while commissioning..
1.When using the  Thread Commissioning App, after selecting the border router, typed the PSKc of the network as admin password. But the app shows **incorrect** password after  5-10 minutes. My doubt is that what is the admin password? is it the PSKc of the network
2. When using the Thread commissioning using CLI commands, after join success when we type the **state** cli command it shows **detached**. What will be the treason
anyone please find the answer for this doubts and help for commissioning the network

**Comment by CiaranWoodward** [comment]
Hi @rohithanayady thanks for creating this issue. Are you using Cascoda hardware and the cascoda SDK for this project? This repository and issue page is specifically for the Cascoda SDK. For other hardware platforms you will be able to find assistance on either the [openthread github](https://github.com/openthread/openthread) or [user group](https://groups.google.com/g/openthread-users?pli=1).

But I'll try and answer your questions anyway:
1. No, the 'Admin Password' refers to the 'commissioning credential' which is defined when the network is first formed. This is used along with some other parameters to create the PSKc (PSKc is basically a hash of this, see section 8.4.1.2.1 of the Thread 1.1.1 spec). It is called 'passphrase' on the openthread border router form network page, I think.
2. Join success is good and means the device has all of the network parameters, including key. But you still need to start the thread stack using the ``thread start`` cli command. The device will then join the network. (Note the network parameters are then stored in nonvolatile storage, so you don't need to commission every time, just ``ifconfig up`` ``thread start``.

**Comment by rohithanayady** [comment]
Hello @CiaranWoodward, i am using the Silicon Lab WSDK hardware.(EFR32MG12)
1.In the **dataset** there is no passphrase is shown. How do we know the passphrase. i think this passphrase is we have to use as the admin password.is it right? Also one more doubt is that if we use a mobile phone as the external commissioner, its name(say eg: vivo1901) is the commissioner credential or admin password? please clarify my doubts
2.No sir. After join success i have typed `thread start` .Then after used the `state.` But it shows**Detached.** What would be the reason. How to get the state as router or child

**Comment by CiaranWoodward** [comment]
Hi @rohithanayady, this repo (and organisation) is for Cascoda hardware - specifically the CA-8210 and CA-8211. Unfortunately we have no experience with any Silicon Labs hardware, so you will need to contact either Silicon Labs' support, or use one of the links I provided above.

1. The passphrase cannot be obtained from the PSKc, as it is created with a one-way function and cannot be extracted. The only way to know the passphrase (which is called the admin key & commissioner credential too) is to choose it when the network is formed.
2. At this point, its difficult to know what went wrong, so I would ask you to check out the silicon labs & openthread generic support. The guide for [Cascoda's hardware](https://github.com/Cascoda/cascoda-sdk/blob/master/docs/guides/thread-commissioning.md#cli-joining) probably won't address your issue.

I hope you can find a solution to your issue, but as it isn't related to the Cascoda SDK or Cascoda hardware, i'm going to close this now.
