### ISSUE TITLE
Delay in Adding Newd Devices

### ISSUE THREAD

**Issue by rohithanayady** [Cascoda/cascoda-sdk#8]
i have successfully achieved the thread commissioning. But now the problem is that the
1. Thread Commissioning App take too much time(5-10 seconds) to add a new device to the network. What will be the reason for this delay?
2. After successfully added the device to the thread network ,` join success` the `thread start`, still it shows the `**state**` as **detached** in the joiner console.
Anyone please tell me the reason for this  problems and how can I rectify it?

**Comment by CiaranWoodward** [comment]
Hi @rohithanayady, this repo (and organisation) is for Cascoda hardware - specifically the CA-8210 and CA-8211. Unfortunately we have no experience with any Silicon Labs hardware, so you will need to contact either Silicon Labs' support, or use one of the links I provided in #7.
